// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['application']['Application']['Connect'](arg1);
}

export function CreateTopic(arg1, arg2, arg3, arg4) {
  return window['go']['application']['Application']['CreateTopic'](arg1, arg2, arg3, arg4);
}

export function DeleteTopic(arg1, arg2) {
  return window['go']['application']['Application']['DeleteTopic'](arg1, arg2);
}

export function GetConfigs() {
  return window['go']['application']['Application']['GetConfigs']();
}

export function GetTopics(arg1) {
  return window['go']['application']['Application']['GetTopics'](arg1);
}
