// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kafka} from '../models';
import {application} from '../models';

export function Connect(arg1:string):Promise<Error>;

export function CreateTopic(arg1:string,arg2:string,arg3:number,arg4:number):Promise<kafka.Topic>;

export function DeleteTopic(arg1:string,arg2:string):Promise<Error>;

export function GetConfigs():Promise<application.Config>;

export function GetTopics(arg1:string):Promise<Array<kafka.Topic>>;
